#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path


def c_escape_bytes(data: bytes) -> str:
    out: list[str] = []
    for b in data:
        if b == 0x5C:  # backslash
            out.append("\\\\")
        elif b == 0x22:  # quote
            out.append('\\"')
        elif b == 0x0A:
            out.append("\\n")
        elif b == 0x0D:
            out.append("\\r")
        elif 0x20 <= b <= 0x7E:
            out.append(chr(b))
        else:
            out.append(f"\\x{b:02x}")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", required=True, help="Path to repo root (contains configs/)")
    ap.add_argument("--out", required=True, help="Output header path")
    args = ap.parse_args()

    repo_root = Path(args.repo_root).resolve()
    src = repo_root / "configs" / "network.json"
    out = Path(args.out).resolve()

    data = src.read_bytes()
    escaped = c_escape_bytes(data)

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "#ifndef DEFAULT_CONFIGS_H\n"
        "#define DEFAULT_CONFIGS_H\n"
        "\n"
        "/* Autogenerated by src/scripts/gen_default_configs.py. */\n"
        "\n"
        f"static const char DEFAULT_NETWORK_JSON[] = \"{escaped}\";\n"
        f"static const unsigned int DEFAULT_NETWORK_JSON_LEN = {len(data)}u;\n"
        "\n"
        "#endif /* DEFAULT_CONFIGS_H */\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
