#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import re


def c_escape_bytes(data: bytes) -> str:
    out: list[str] = []
    for b in data:
        if b == 0x5C:  # backslash
            out.append("\\\\")
        elif b == 0x22:  # quote
            out.append('\\"')
        elif b == 0x0A:
            out.append("\\n")
        elif b == 0x0D:
            out.append("\\r")
        elif 0x20 <= b <= 0x7E:
            out.append(chr(b))
        else:
            out.append(f"\\x{b:02x}")
    return "".join(out)


def c_ident_from_filename(name: str) -> str:
    stem = Path(name).stem
    s = re.sub(r"[^a-zA-Z0-9]+", "_", stem).strip("_")
    if not s:
        s = "I2C_DEVICE"
    if s[0].isdigit():
        s = "_" + s
    return s.upper()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo-root", required=True, help="Path to repo root (contains configs/)")
    ap.add_argument("--out", required=True, help="Output header path")
    args = ap.parse_args()

    repo_root = Path(args.repo_root).resolve()
    src_dir = repo_root / "configs"
    network_src = src_dir / "network.json"
    i2c_dir = src_dir / "i2c"
    out = Path(args.out).resolve()

    net_data = network_src.read_bytes()
    net_escaped = c_escape_bytes(net_data)

    i2c_files: list[tuple[str, bytes, str]] = []
    if i2c_dir.exists():
        for p in sorted(i2c_dir.glob("*.json")):
            data = p.read_bytes()
            i2c_files.append((p.name, data, c_escape_bytes(data)))

    out.parent.mkdir(parents=True, exist_ok=True)
    parts: list[str] = []
    parts.append("#ifndef DEFAULT_CONFIGS_H\n")
    parts.append("#define DEFAULT_CONFIGS_H\n\n")
    parts.append("/* Autogenerated by src/scripts/gen_default_configs.py. */\n\n")
    parts.append(f"static const char DEFAULT_NETWORK_JSON[] = \"{net_escaped}\";\n")
    parts.append(f"static const unsigned int DEFAULT_NETWORK_JSON_LEN = {len(net_data)}u;\n\n")

    parts.append("typedef struct {\n")
    parts.append("    const char *file_name;\n")
    parts.append("    const char *json;\n")
    parts.append("    unsigned int json_len;\n")
    parts.append("} default_json_file_t;\n\n")

    default_entries: list[str] = []
    for fname, data, escaped in i2c_files:
        ident = c_ident_from_filename(fname)
        parts.append(f"static const char DEFAULT_I2C_{ident}_JSON[] = \"{escaped}\";\n")
        parts.append(f"static const unsigned int DEFAULT_I2C_{ident}_JSON_LEN = {len(data)}u;\n\n")
        default_entries.append(f"    {{ \"{fname}\", DEFAULT_I2C_{ident}_JSON, DEFAULT_I2C_{ident}_JSON_LEN }},\n")

    if not default_entries:
        parts.append("static const default_json_file_t DEFAULT_I2C_CONFIG_FILES[] = { };\n")
        parts.append("static const unsigned int DEFAULT_I2C_CONFIG_FILES_COUNT = 0u;\n\n")
    else:
        parts.append("static const default_json_file_t DEFAULT_I2C_CONFIG_FILES[] = {\n")
        parts.extend(default_entries)
        parts.append("};\n")
        parts.append(f"static const unsigned int DEFAULT_I2C_CONFIG_FILES_COUNT = {len(default_entries)}u;\n\n")

    parts.append("#endif /* DEFAULT_CONFIGS_H */\n")

    out.write_text(
        "".join(parts),
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
