#ifndef BVSTK_PL_I2C_REGS_H
#define BVSTK_PL_I2C_REGS_H

#include <stdint.h>

#define BVSTK_I2C_SLV_CSR_OFFSET       UINT32_C(0x00)
#define BVSTK_I2C_SLV_IRQ_OFFSET       UINT32_C(0x04)
#define BVSTK_I2C_SLV_REQ_OFFSET       UINT32_C(0x08)
#define BVSTK_I2C_SLV_ADDR_LIST_0      UINT32_C(0x10)
#define BVSTK_I2C_SLV_ADDR_LIST_1      UINT32_C(0x14)
#define BVSTK_I2C_SLV_ADDR_LIST_2      UINT32_C(0x18)
#define BVSTK_I2C_SLV_ADDR_LIST_3      UINT32_C(0x1C)

#define BVSTK_I2C_SLV_CSR_SOFT_RESET_BIT (UINT32_C(1) << 0)
#define BVSTK_I2C_SLV_CSR_START_BIT      (UINT32_C(1) << 1)
#define BVSTK_I2C_SLV_CSR_RD_VALID_BIT   (UINT32_C(1) << 2)

#define BVSTK_I2C_SLV_IRQ_RESET_BIT      (UINT32_C(1) << 0)
#define BVSTK_I2C_SLV_IRQ_DATA_VALID    (UINT32_C(1) << 1)
#define BVSTK_I2C_SLV_IRQ_FINAL_PACKET  (UINT32_C(1) << 2)
#define BVSTK_I2C_SLV_IRQ_RD_REQUEST    (UINT32_C(1) << 3)
#define BVSTK_I2C_SLV_IRQ_ERR_ACK       (UINT32_C(1) << 4)
#define BVSTK_I2C_SLV_IRQ_MEM_OVERFLOW  (UINT32_C(1) << 5)

#define BVSTK_I2C_SLV_HEADER_ADDR_MASK  UINT32_C(0x7F)
#define BVSTK_I2C_SLV_HEADER_BYTES_SHIFT 7U
#define BVSTK_I2C_SLV_HEADER_BYTES_MASK \
    (UINT32_C(0x01FFFFFF) << BVSTK_I2C_SLV_HEADER_BYTES_SHIFT)

#define BVSTK_I2C_MSTR_CSR_OFFSET      UINT32_C(0x00)
#define BVSTK_I2C_MSTR_IRQ_OFFSET      UINT32_C(0x04)
#define BVSTK_I2C_MSTR_TX_FIFO_OFFSET  UINT32_C(0x08)
#define BVSTK_I2C_MSTR_TIMEOUT_OFFSET  UINT32_C(0x0C)

#define BVSTK_I2C_BRAM_MASTER_OFFSET   UINT32_C(0x0000)
#define BVSTK_I2C_BRAM_MASTER_WINDOW_SIZE UINT32_C(0x1000)
#define BVSTK_I2C_BRAM_SLAVE_WR_OFFSET UINT32_C(0x1000)
#define BVSTK_I2C_BRAM_SLAVE_RD_OFFSET UINT32_C(0x2000)
#define BVSTK_I2C_BRAM_SLAVE_WINDOW_SIZE UINT32_C(0x1000)

#define BVSTK_I2C_MSTR_SOFT_RESET_BIT  (UINT32_C(1) << 0)
#define BVSTK_I2C_MSTR_START_BIT       (UINT32_C(1) << 1)

#endif /* BVSTK_PL_I2C_REGS_H */
