#ifndef BVSTK_SPI_REGS_H
#define BVSTK_SPI_REGS_H

#include <stdint.h>

#define BVSTK_SPI_CSR_OFFSET      UINT32_C(0x00)
#define BVSTK_SPI_IRQ_OFFSET      UINT32_C(0x04)
#define BVSTK_SPI_PACKET_OFFSET   UINT32_C(0x08)
#define BVSTK_SPI_TIMEOUT_OFFSET  UINT32_C(0x0C)
#define BVSTK_SPI_TX_FIFO_OFFSET  UINT32_C(0x10)
#define BVSTK_SPI_SD_INI_OFFSET   UINT32_C(0x14)
#define BVSTK_SPI_SIGNATURE_OFFSET UINT32_C(0x18)

#define BVSTK_SPI_MODE_SINGLE      UINT32_C(0x1)
#define BVSTK_SPI_MODE_MULTI       UINT32_C(0x2)
#define BVSTK_SPI_MODE_FALLTHROUGH UINT32_C(0x3)

#endif
