#ifndef BVSTK_PL_SMI_REGS_H
#define BVSTK_PL_SMI_REGS_H

#include <stdint.h>

#define BVSTK_SMI_MASTER_WR_OFFSET UINT32_C(0x0000)
#define BVSTK_SMI_SLAVE_WR_OFFSET  UINT32_C(0x1000)
#define BVSTK_SMI_SLAVE_RD_OFFSET  UINT32_C(0x2000)

#define BVSTK_SMI_MSTR_CSR_OFFSET      UINT32_C(0x00)
#define BVSTK_SMI_MSTR_TIMEOUT_OFFSET  UINT32_C(0x04)
#define BVSTK_SMI_MSTR_IRQ_OFFSET      UINT32_C(0x08)
#define BVSTK_SMI_MSTR_TX_FIFO_OFFSET  UINT32_C(0x0C)
#define BVSTK_SMI_MSTR_MEM_ADDR_OFFSET UINT32_C(0x10)

#define BVSTK_SMI_SLV_CSR_OFFSET      UINT32_C(0x00)
#define BVSTK_SMI_SLV_MEM_ADDR_OFFSET UINT32_C(0x04)
#define BVSTK_SMI_SLV_IRQ_OFFSET      UINT32_C(0x08)
#define BVSTK_SMI_SLV_S2H_OFFSET      UINT32_C(0x0C)

#endif /* BVSTK_PL_SMI_REGS_H */
