#ifndef DEFAULT_CONFIGS_H
#define DEFAULT_CONFIGS_H

/* Autogenerated by src/scripts/gen_default_configs.py. */

static const char DEFAULT_NETWORK_JSON[] = "{\n  \"ipv4\": {\n    \"ip\": \"192.168.0.10\",\n    \"netmask\": \"255.255.255.0\",\n    \"gateway\": \"192.168.0.1\"\n  },\n  \"mac\": \"00:0a:35:00:01:02\"\n}\n\n";
static const unsigned int DEFAULT_NETWORK_JSON_LEN = 138u;

#endif /* DEFAULT_CONFIGS_H */
