#ifndef BVSTK_PL_SD_REGS_H
#define BVSTK_PL_SD_REGS_H

#include <stdint.h>

/* Byte offsets in the AXI4-Lite register window of sd_spi_controller. */
#define BVSTK_SD_CONTROL_OFFSET       UINT32_C(0x00)
#define BVSTK_SD_STATUS_OFFSET        UINT32_C(0x04)
#define BVSTK_SD_BLOCK_OFFSET         UINT32_C(0x08)
#define BVSTK_SD_DATA_OFFSET          UINT32_C(0x0c)
#define BVSTK_SD_BUFFER_INDEX_OFFSET  UINT32_C(0x10)
#define BVSTK_SD_CLOCK_DIV_OFFSET     UINT32_C(0x14)
#define BVSTK_SD_ERROR_OFFSET         UINT32_C(0x18)

/* Read-only protocol diagnostics. */
#define BVSTK_SD_DEBUG_STATE_OFFSET        UINT32_C(0x1c)
#define BVSTK_SD_DEBUG_COUNTERS_OFFSET     UINT32_C(0x20)
#define BVSTK_SD_DEBUG_LAST_CMD_HI_OFFSET  UINT32_C(0x24)
#define BVSTK_SD_DEBUG_LAST_CMD_LO_OFFSET  UINT32_C(0x28)
#define BVSTK_SD_DEBUG_RESPONSE_OFFSET     UINT32_C(0x2c)
#define BVSTK_SD_DEBUG_ACMD41_OFFSET       UINT32_C(0x30)
#define BVSTK_SD_DEBUG_CMD55_OFFSET        UINT32_C(0x34)
#define BVSTK_SD_DEBUG_PINS_OFFSET         UINT32_C(0x38)
#define BVSTK_SD_DEBUG_TRACE_INDEX_OFFSET  UINT32_C(0x3c)
#define BVSTK_SD_DEBUG_TRACE_DATA_OFFSET   UINT32_C(0x40)
#define BVSTK_SD_DEBUG_CMD55_HI_OFFSET     UINT32_C(0x44)
#define BVSTK_SD_DEBUG_CMD55_LO_OFFSET     UINT32_C(0x48)
#define BVSTK_SD_DEBUG_CMD41_HI_OFFSET     UINT32_C(0x4c)
#define BVSTK_SD_DEBUG_CMD41_LO_OFFSET     UINT32_C(0x50)
#define BVSTK_SD_DEBUG_LAST_BYTE_OFFSET    UINT32_C(0x54)
#define BVSTK_SD_DEBUG_DIAG_OFFSET         UINT32_C(0x58)

#define BVSTK_SD_CONTROL_INIT         (UINT32_C(1) << 0)
#define BVSTK_SD_CONTROL_READ         (UINT32_C(1) << 1)
#define BVSTK_SD_CONTROL_WRITE        (UINT32_C(1) << 2)
#define BVSTK_SD_CONTROL_CLEAR        (UINT32_C(1) << 3)

#define BVSTK_SD_STATUS_BUSY          (UINT32_C(1) << 0)
#define BVSTK_SD_STATUS_DONE          (UINT32_C(1) << 1)
#define BVSTK_SD_STATUS_ERROR         (UINT32_C(1) << 2)
#define BVSTK_SD_STATUS_INITIALIZED   (UINT32_C(1) << 3)
#define BVSTK_SD_STATUS_HIGH_CAPACITY (UINT32_C(1) << 4)
#define BVSTK_SD_STATUS_INIT_ACTIVE  (UINT32_C(1) << 5)
#define BVSTK_SD_STATUS_ERROR_SHIFT   8U
#define BVSTK_SD_STATUS_ERROR_MASK    UINT32_C(0x0000ff00)
#define BVSTK_SD_STATUS_LAST_R1_SHIFT 16U
#define BVSTK_SD_STATUS_LAST_R1_MASK  UINT32_C(0x00ff0000)
#define BVSTK_SD_STATUS_CURRENT_CMD_SHIFT 24U
#define BVSTK_SD_STATUS_CURRENT_CMD_MASK  UINT32_C(0x3f000000)

#define BVSTK_SD_ERROR_CODE_MASK      UINT32_C(0x000000ff)
#define BVSTK_SD_ERROR_LAST_R1_SHIFT  8U
#define BVSTK_SD_ERROR_LAST_R1_MASK   UINT32_C(0x0000ff00)

/* DEBUG_STATE fields. */
#define BVSTK_SD_DEBUG_STATE_STATE_MASK        UINT32_C(0x0000001f)
#define BVSTK_SD_DEBUG_STATE_CS_N              (UINT32_C(1) << 5)
#define BVSTK_SD_DEBUG_STATE_SPI_BUSY         (UINT32_C(1) << 6)
#define BVSTK_SD_DEBUG_STATE_SPI_DONE         (UINT32_C(1) << 7)
#define BVSTK_SD_DEBUG_STATE_SCK              (UINT32_C(1) << 8)
#define BVSTK_SD_DEBUG_STATE_MOSI             (UINT32_C(1) << 9)
#define BVSTK_SD_DEBUG_STATE_MISO             (UINT32_C(1) << 10)
#define BVSTK_SD_DEBUG_STATE_INIT_ACTIVE      (UINT32_C(1) << 11)
#define BVSTK_SD_DEBUG_STATE_CURRENT_CMD_SHIFT 12U
#define BVSTK_SD_DEBUG_STATE_CURRENT_CMD_MASK UINT32_C(0x0003f000)
#define BVSTK_SD_DEBUG_STATE_LAST_R1_SHIFT    18U
#define BVSTK_SD_DEBUG_STATE_LAST_R1_MASK     UINT32_C(0x03fc0000)

/* DEBUG_CMD55 fields. */
#define BVSTK_SD_DEBUG_CMD55_R1_MASK          UINT32_C(0x000000ff)
#define BVSTK_SD_DEBUG_CMD41_R1_SHIFT         8U
#define BVSTK_SD_DEBUG_CMD41_R1_MASK          UINT32_C(0x0000ff00)
#define BVSTK_SD_DEBUG_CMD41_AFTER_CMD55      (UINT32_C(1) << 16)
#define BVSTK_SD_DEBUG_CMD55_ACCEPTED        (UINT32_C(1) << 17)
#define BVSTK_SD_DEBUG_COMPLETED_CMD_SHIFT   18U
#define BVSTK_SD_DEBUG_COMPLETED_CMD_MASK    UINT32_C(0x00fc0000)
#define BVSTK_SD_DEBUG_STARTED_CMD_SHIFT     24U
#define BVSTK_SD_DEBUG_STARTED_CMD_MASK      UINT32_C(0x3f000000)

/* DEBUG_ACMD41 fields. */
#define BVSTK_SD_DEBUG_ACMD41_RETRY_SHIFT    0U
#define BVSTK_SD_DEBUG_ACMD41_RETRY_MASK     UINT32_C(0x0000ffff)
#define BVSTK_SD_DEBUG_ACMD41_COUNT_SHIFT    16U
#define BVSTK_SD_DEBUG_ACMD41_COUNT_MASK     UINT32_C(0xffff0000)

/* DEBUG_DIAG fields. */
#define BVSTK_SD_DEBUG_TRACE_WRITE_PTR_MASK  UINT32_C(0x0000001f)
#define BVSTK_SD_DEBUG_RESPONSE_COUNT_SHIFT 5U
#define BVSTK_SD_DEBUG_RESPONSE_COUNT_MASK  UINT32_C(0x000000e0)
#define BVSTK_SD_DEBUG_SPI_BYTE_COUNT_SHIFT 8U
#define BVSTK_SD_DEBUG_SPI_BYTE_COUNT_MASK  UINT32_C(0x00ffff00)

#endif /* BVSTK_PL_SD_REGS_H */
