#!/usr/bin/env python3
"""Generate build-local SSH credentials for the FreeRTOS image.

The generated header is intentionally ignored by Git.  The password is stored
only as a SHA-256 digest and the host private key is embedded because the
firmware has no filesystem dependency for its SSH listener.
"""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import subprocess
import tempfile


def c_bytes(data: bytes) -> str:
    return ", ".join(f"0x{value:02x}" for value in data)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    password = os.environ.get("BVSTK_SSH_PASSWORD")
    if not password:
        raise SystemExit("BVSTK_SSH_PASSWORD must be set when SSH is enabled")

    host_key_path = os.environ.get("BVSTK_SSH_HOST_KEY")
    temporary_key: Path | None = None
    try:
        if host_key_path:
            host_key = Path(host_key_path).read_bytes()
        else:
            with tempfile.NamedTemporaryFile(prefix="bvstk-ssh-host-", suffix=".pem", delete=False) as key_file:
                temporary_key = Path(key_file.name)
            subprocess.run(
                ["openssl", "genrsa", "-traditional", "-out", str(temporary_key), "2048"],
                check=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            host_key = temporary_key.read_bytes()
    finally:
        if temporary_key is not None:
            temporary_key.unlink(missing_ok=True)

    digest = hashlib.sha256(password.encode("utf-8")).digest()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    text = f"""/* Generated by scripts/ssh/generate_config.py. Do not commit. */
#ifndef BVSTK_SSH_GENERATED_H
#define BVSTK_SSH_GENERATED_H

#define BVSTK_SSH_USER \"{os.environ.get('BVSTK_SSH_USER', 'root')}\"
#define BVSTK_SSH_PORT {int(os.environ.get('BVSTK_SSH_PORT', '22'))}

static const unsigned char bvstk_ssh_password_sha256[] = {{ {c_bytes(digest)} }};
#define BVSTK_SSH_PASSWORD_SHA256_SIZE (sizeof(bvstk_ssh_password_sha256))

static const unsigned char bvstk_ssh_host_key[] = {{ {c_bytes(host_key)} }};
#define BVSTK_SSH_HOST_KEY_SIZE (sizeof(bvstk_ssh_host_key))

#endif
"""
    args.output.write_text(text, encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
